---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  project: system
  source:
    path: argocd/system/metallb
    repoURL: git@git.andybug.com:andy/k8s0.git
    targetRevision: HEAD
