---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: system
  source:
    path: argocd/system/argocd
    repoURL: git@git.andybug.com:andy/k8s0.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: system
  source:
    path: argocd/system/metallb
    repoURL: git@git.andybug.com:andy/k8s0.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: system
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 9.11.0
    helm:
      values: |-
        additionalArguments:
          - "--providers.kubernetesingress.ingressclass=traefik-lb"
          - "--metrics.prometheus"
    chart: traefik
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  destination:
    namespace: longhorn
    server: https://kubernetes.default.svc
  project: system
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.1.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-dns
# spec:
#   destination:
#     namespace: external-dns
#     server: https://kubernetes.default.svc
#   project: system
#   source:
#     path: argocd/system/external-dns
#     repoURL: git@git.andybug.com:andy/k8s0.git
#     targetRevision: HEAD
