---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-k8s0-weirwd-net
  namespace: linkerd
spec:
  secretName: linkerd-k8s0-weirwd-net-tls
  duration: 72h
  renewBefore: 24h
  commonName: linkerd.k8s0.weirwd.net
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - linkerd.k8s0.weirwd.net
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkerd-k8s0-weirwd-net
  namespace: linkerd
spec:
  tls:
  - hosts:
      - linkerd.k8s0.weirwd.net
    secretName: linkerd-k8s0-weirwd-net-tls
  rules:
  - host: linkerd.k8s0.weirwd.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkerd-web
            port:
              number: 8084
