---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-k8s0-weirwd-net
  namespace: prometheus
spec:
  secretName: prometheus-k8s0-weirwd-net-tls
  duration: 720h0m0s
  renewBefore: 168h0m0s
  commonName: prometheus.k8s0.weirwd.net
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - prometheus.k8s0.weirwd.net
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
