---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/weirwd-dot-net
    server: https://vault.vault.svc.cluster.local
    caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIDIzCCAgugAwIBAgIUO3Z+tM+LrzAHKhwi7jaX6EmyUdswDQYJKoZIhvcNAQEL
        BQAwGTEXMBUGA1UEAxMOV2VpcndkIFJvb3QgQ0EwHhcNMjAxMjE5MTQzNDQxWhcN
        MzAxMjE3MTQzNTEwWjAZMRcwFQYDVQQDEw5XZWlyd2QgUm9vdCBDQTCCASIwDQYJ
        KoZIhvcNAQEBBQADggEPADCCAQoCggEBAK21zhahzLrLwIKvoxDh+Ond0hkCJZ1P
        WigAzfTGYvLHsVrYdkr5U3py0HsEBKsk5qI6Q6WlyB1wxHYS4NxvL8xLEvnkFZT9
        yauY1n+Wrd4RBoCgbBNubg3+Ek897V3XfOxKK9LempxrOU8LpfMIovoJZoM9PYYE
        oJGXPcLmdsmZNGMrlYnySoWmsaG25Iqk8BKR83Ns4ek4caG7NSHR05uxeK5jtTGJ
        gmjWTWjlFOpjFBMnPY9c8SyWYyVZdmZOgffeTh8kdXauPpLiVWZSUuBFczVYRiHB
        YhVglUTqd7zAjr9t2Cj7VpOBCo8IjUtFi1TnYs8gq4wK+YleEyH/Qo8CAwEAAaNj
        MGEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFNxz
        1vWgT40+teuwR2RHNDqiF0XnMB8GA1UdIwQYMBaAFNxz1vWgT40+teuwR2RHNDqi
        F0XnMA0GCSqGSIb3DQEBCwUAA4IBAQCZLAd6eUZYBaI+DLSxtXV1R5q07kZkCQUO
        V0yaEJ+auqcW8yFCAkTlBz7c8BmdtmZzmm47fkwu2x1+bRljy5aM8XQhwk4b/yBY
        0lMKzKlpleftX/PlwQJK5rTz5UsqBagItxwqQhqj/R53dI6Vl8tP8sdtPNMNR472
        4eh/FU6j3GoSiwpLV2O67+HxTxiO5WMSTCmDNnodgLz+mpaefHtYISgKo8FDniXV
        vcJy4kSeCydxFEFRSoqOZTDzZEqiKoU2zLgK5hi11nM8DgTiTmpv2yzNMxWoTB3w
        OputbKnghA5CQn1lSLjNQZwmnuh6cUtRP3nYo7r4mdwb/tDnvfPJ
        -----END CERTIFICATE-----
    auth:
      appRole:
        path: approle
        roleId: df4256f8-3184-5ac2-d391-1affd6795325
        secretRef:
          name: vault-approle
          key: secretId
