---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/weirwd-dot-net
    server: https://vault.vault.svc.cluster.local
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lVTzNaK3RNK0xyekFIS2h3aTdqYVg2RW15VWRzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF4TU9WMlZwY25ka0lGSnZiM1FnUTBFd0hoY05NakF4TWpFNU1UUXpORFF4V2hjTgpNekF4TWpFM01UUXpOVEV3V2pBWk1SY3dGUVlEVlFRREV3NVhaV2x5ZDJRZ1VtOXZkQ0JEUVRDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUsyMXpoYWh6THJMd0lLdm94RGgrT25kMGhrQ0paMVAKV2lnQXpmVEdZdkxIc1ZyWWRrcjVVM3B5MEhzRUJLc2s1cUk2UTZXbHlCMXd4SFlTNE54dkw4eExFdm5rRlpUOQp5YXVZMW4rV3JkNFJCb0NnYkJOdWJnMytFazg5N1YzWGZPeEtLOUxlbXB4ck9VOExwZk1Jb3ZvSlpvTTlQWVlFCm9KR1hQY0xtZHNtWk5HTXJsWW55U29XbXNhRzI1SXFrOEJLUjgzTnM0ZWs0Y2FHN05TSFIwNXV4ZUs1anRUR0oKZ21qV1RXamxGT3BqRkJNblBZOWM4U3lXWXlWWmRtWk9nZmZlVGg4a2RYYXVQcExpVldaU1V1QkZjelZZUmlIQgpZaFZnbFVUcWQ3ekFqcjl0MkNqN1ZwT0JDbzhJalV0RmkxVG5ZczhncTR3SytZbGVFeUgvUW84Q0F3RUFBYU5qCk1HRXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOeHoKMXZXZ1Q0MCt0ZXV3UjJSSE5EcWlGMFhuTUI4R0ExVWRJd1FZTUJhQUZOeHoxdldnVDQwK3RldXdSMlJITkRxaQpGMFhuTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDWkxBZDZlVVpZQmFJK0RMU3h0WFYxUjVxMDdrWmtDUVVPClYweWFFSithdXFjVzh5RkNBa1RsQno3YzhCbWR0bVp6bW00N2Zrd3UyeDErYlJsank1YU04WFFod2s0Yi95QlkKMGxNS3pLbHBsZWZ0WC9QbHdRSks1clR6NVVzcUJhZ0l0eHdxUWhxai9SNTNkSTZWbDh0UDhzZHRQTk1OUjQ3Mgo0ZWgvRlU2ajNHb1Npd3BMVjJPNjcrSHhUeGlPNVdNU1RDbURObm9kZ0x6K21wYWVmSHRZSVNnS284RkRuaVhWCnZjSnk0a1NlQ3lkeEZFRlJTb3FPWlREelpFcWlLb1UyekxnSzVoaTExbk04RGdUaVRtcHYyeXpOTXhXb1RCM3cKT3B1dGJLbmdoQTVDUW4xbFNMak5RWndtbnVoNmNVdFJQM25ZbzdyNG1kd2IvdERudmZQSgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    auth:
      appRole:
        path: approle
        roleId: df4256f8-3184-5ac2-d391-1affd6795325
        secretRef:
          name: vault-approle
          key: secretId
