apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - base/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v1.8.1/manifests/install.yaml
patchesStrategicMerge:
  - overlays/production/argocd-cm.yaml
images:
  - name: argoproj/argocd
    newName: cyrilix/argocd
    newTag: v1.8.1
