---
- name: set kernel cmdline options
  ansible.builtin.copy:
    dest: /boot/firmware/cmdline.txt
    content: |
      net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1
  tags:
    - never
    - node:cmdline

- name: start and enable iscsid
  ansible.builtin.systemd:
    name: iscsid.service
    enabled: yes
    state: started
  tags:
    - node:iscsi
    - node:iscsid

- name: longhorn directory
  ansible.builtin.file:
    path: /var/lib/longhorn
    state: directory
  tags:
    - node:longhorn

- name: format data partition
  community.general.filesystem:
    dev: '{{ node_data_partition }}'
    force: no
    fstype: ext4
    opts: -L longhorn
  tags:
    - node:longhorn

- name: mount longhorn partition
  ansible.posix.mount:
    path: /var/lib/longhorn
    src: LABEL=longhorn
    fstype: ext4
    opts: defaults
    state: mounted
  tags:
    - node:longhorn
