apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph-0
spec:
  cephVersion:
    image: ceph/ceph:v15.2.7
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
  dashboard:
    enabled: true
  # cluster level storage configuration and selection
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: 'mmcblk0p3'
    config:
      metadataDevice:
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      osdsPerDevice: "1"
  healthCheck:
    livenessProbe:
      mgr:
        disabled: false
        probe:
          # httpGet:
          #   path: /
          #   port: 9283
          initialDelaySeconds: 180
          # periodSeconds: 3
