---
# these are not used
# keeping for reference in case we revist it

- name: configure iptables
  tags:
    - ubuntu:iptables
    - iptables
  block:
    - name: tempfile for iptables rules
      ansible.builtin.tempfile:
        state: file
        suffix: .rules
      register: iptables_rules_tempfile
      changed_when: false
      when: not ansible_check_mode

    - name: save iptables rules
      ansible.builtin.command:
        argv:
          - /sbin/iptables-save
          - -f
          - '{{ iptables_rules_tempfile.path }}'
      changed_when: false
      when: not ansible_check_mode

    - name: create DEFAULT-INPUT chain
      ansible.builtin.command:
        argv:
          - /sbin/iptables
          - -N
          - DEFAULT-INPUT
      register: result
      changed_when: "result.rc == 0"
      failed_when: false
      when: not ansible_check_mode

    - name: allow related and established connections
      iptables:
        chain: DEFAULT-INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      notify:
        - netfilter-save

    - name: allow inbound traffic on loopback
      iptables:
        chain: DEFAULT-INPUT
        in_interface: lo
        jump: ACCEPT
      notify:
        - netfilter-save

    - name: allow new ssh connections
      iptables:
        chain: DEFAULT-INPUT
        source: '{{ cluster_ssh_allowed_cidr }}'
        destination_port: '22'
        protocol: tcp
        ctstate: NEW
        syn: match
        jump: ACCEPT
      notify:
        - netfilter-save

    # INPUT

    - name: INPUT jump to DEFAULT-INPUT
      iptables:
        chain: INPUT
        jump: DEFAULT-INPUT
      notify:
        - netfilter-save

    - name: set policy for INPUT chain to DROP
      iptables:
        chain: INPUT
        policy: ACCEPT # FIXME
      notify:
        - netfilter-save

    # FORWARD

    - name: set policy for FORWARD chain to DROP
      iptables:
        chain: FORWARD
        policy: DROP
      notify:
        - netfilter-save

    # OUTPUT

    - name: set policy for OUTPUT chain to ACCEPT
      iptables:
        chain: OUTPUT
        policy: ACCEPT
      notify:
        - netfilter-save

  rescue:
    - name: restore iptables rules
      ansible.builtin.command:
        argv:
          - /sbin/iptables-restore
          - '{{ iptables_rules_tempfile.path }}'
      when: not ansible_check_mode

  always:
    - name: remove tempfile
      ansible.builtin.file:
        path: '{{ iptables_rules_tempfile.path }}'
        state: absent
      changed_when: false
      when: |
        iptables_rules_tempfile.path is defined
        and not ansible_check_mode

- name: enable iptables service (netfilter)
  systemd:
    name: iptables.service
    enabled: true
  tags:
    - ubuntu-iptables
    - iptables
