---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - github.com/kubernetes-sigs/external-dns//kustomize?ref=v0.7.5

commonLabels:
  app.kubernetes.io/name: external-dns
  app.kubernetes.io/version: 0.7.5

patchesStrategicMerge:
  - deployment-env.yaml

patchesJson6902:
- target:
    version: apps/v1
    kind: Deployment
    name: external-dns
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: '--provider=aws'
